# Maximum number of items returned per cell execution. Additional items will be truncated.
# Unit: count / number of items
resultSizeLimit: 1000

# Maximum size of a cell result. If a cell result exceeds this size then the cell execution will fail.
# Unit: bytes
maxResultSizeBytes: 10485760

# Cell execution timeout. A value of 0 indicates no timeout and will depend on the DSE server timeouts configured in dse.yaml.
# Unit: miliseconds
executionTimeoutMs: 0

# Schema refresh polling interval.
# Unit: miliseconds
schemaRefreshIntervalMs: 3000

# TraversalSource mapping for real-time and analytic execution engines. These values correspond to the traversal sources
# configured in dse.yaml.
# Unit: string
traversalSources:
  realTimeTraversalSource: g
  analyticTraversalSource: a

# This refers to the datastax-studio server
server:
 httpPort: 8088
 httpBindAddress: localhost

# User data being, where we store data specific to a user
# in the application.  For the short-term this is the file system, which
# is why we need to explicitly configure a location
userData:
  #defaults to a .datastax_studio folder in your home directory, such as  ~/.datastax_studio
  #set to a non-null value to override
  baseDirectory: null
  connectionsDirectory: connections
  notebooksDirectory: notebooks

connectionManagement:
  #how long before we expire/close a connection that isn't in use.
  #Defaulting to 1 hour
  idleTimeoutInSeconds: 3600

