# Maximum number of items returned per cell execution. Additional items will be truncated.
# Unit: count / number of items
resultSizeLimit: 1000

# Cell execution timeout. A value of 0 indicates no timeout and will depend on the DSE server timeouts configured in dse.yaml.
# Unit: miliseconds
executionTimeoutMs: 0

# This refers to the datastax-studio server
server:
 httpPort: 8088
 httpBindAddress: localhos

logging:
 fileName: studio.log
 maxLogFileSize: 250 MB
 maxFiles: 10
 directory: ./logs

# User data being, where we store data specific to a user
# in the application.  For the short-term this is the file system, which
# is why we need to explicitly configure a location
userData:
  #defaults to a .datastax_studio folder in your home directory, such as  ~/.datastax_studio
  #set to a non-null value to override
  baseDirectory: null
  connectionsDirectory: connections
  notebooksDirectory: notebooks

